Contact form
Tracy-miranja/Portfolio pull request #7
Opened 2022-12-07 15:53 UTC by Tracy-miranja

i  have added a contact form and linked it with my form spree.

2022-12-07 17:17 UTC, amejid requested changes
Hi @Tracy-miranja, @martinkarugaba, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Good commit history :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 
- Formspree correctly setup :heavy_check_mark: 
- Linter checks passing :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 09:16 UTC, Tadesse-Alemayehu requested changes
### Hi @Tracy-miranja 
### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [ ] Good job making most of the changes requested by the previous reviewer. 🙏
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  All linters passed 🥇

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 09:16 UTC, Tadesse-Alemayehu commented on index.html
> +    </footer>
##### Impressive changes you made @Tracy-miranja. But There are some minor details we need to address to get your design close to the Figma design.
- [ ] Please make sure to use the right font as defined in the Figma design. In your case please use `Inter` font family.
- [ ] Please make sure your `about` content is aligned to the center as shown in the Figma design.

### Figma design
![Screenshot 2022-12-07 203111](https://user-images.githubusercontent.com/69077061/206406387-5a1b0e50-06b6-4dce-a1be-4c6f08ae77f5.png)

### Your design
![Screenshot 2022-12-07 203211](https://user-images.githubusercontent.com/69077061/206406390-648b1736-2ed1-4a8d-bd1b-9888dd4c5689.png)

2022-12-08 10:15 UTC, DuaneDave approved these changes
Hi @Tracy-miranja and @Tadesse-Alemayehu 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Great implementing changes from the first review 💯 
✔️ Nice UI 💯 

## Optional suggestions
- This project is being approved based on the first reviewer's comments but as the second reviewer has said, I strongly recommend changing the fonts for this project to match the one in the Figma template as this will make the UI much better.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 10:25 UTC, merged